app: Pinem
port: 8080
host: 127.0.0.1
secret:

db:
  port:
  host:
  name:
  user:
  password:

redis:
  port:
  host:
  db:
  password:

i18n:
  default: en
  dir: config/locale

token:
  expires_at: 2592000
